#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'
shell_integration = true
terminal_background = '#232a2e'

[[blocks]]
type = 'prompt'
alignment = 'left'
filler = '.'
newline = true

[[blocks.segments]]
type = 'path'
style = 'plain'
foreground = '#83c092'
template = '{{ .Path }}'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = '#343f44'
template = ' |'

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = '#e69875'
template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }} '

[blocks.segments.properties]
branch_max_length = 25
fetch_status = true
fetch_upstream_icon = true
branch_icon = ''

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = '#dbbc7f'
template = '{{ .FormattedMs  }}'

[blocks.segments.properties]
threshold = 5000

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
  "{{if gt .Code 0}}#e67e80{{end}}",
  "{{if eq .Code 0}}#7fbbb3{{end}}",
]
template = '❯'

[transient_prompt]
foreground_templates = [
  "{{if gt .Code 0}}#e67e80{{end}}",
  "{{if eq .Code 0}}#7fbbb3{{end}}",
]
background = 'transparent'
template = '❯ '


[secondary_prompt]
foreground = '#7fbbb3'
background = 'transparent'
template = '❯❯ '
